{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.systemd;
  inherit (lib)
    attrsets
    lists
    options
    trivial
    types
    ;

  systemdUtils =
    (import (pkgs.path + "/nixos/lib/utils.nix") {
      inherit lib pkgs config;
    }).systemdUtils;

  unitTypes = [
    "path"
    "service"
    "slice"
    "socket"
    "target"
    "timer"
  ];
in
{
  options.systemd = {
    package = lib.mkOption {
      type = types.package;
      default = pkgs.systemd;
      defaultText = lib.literalExpression "pkgs.systemd";
      description = ''
        The systemd package to use.
      '';
    };
    user =
      (trivial.pipe unitTypes [
        (map (
          t:
          attrsets.nameValuePair "${t}s" (
            options.mkOption {
              default = { };
              type = systemdUtils.types."${t}s";
              description = "Definition of systemd per-user ${t} units.";
            }
          )
        ))
        builtins.listToAttrs
      ])
      // {
        packages = options.mkOption {
          type = types.listOf types.package;
          default = [ ];
          description = ''
            Packages containing user units in etc/systemd/user or lib/systemd/user
            to link into /etc/systemd/user. Explicitly declared units take precedence.
          '';
        };
        units = options.mkOption {
          type = systemdUtils.types.units;
          default = { };
          internal = true;
          description = "Internal systemd user unit option to handle transformations.";
        };
      };
    globalEnvironment = lib.mkOption {
      type = types.attrsOf (
        types.nullOr (
          types.oneOf [
            types.str
            types.path
            types.package
          ]
        )
      );
      default = { };
      example = {
        TZ = "CET";
      };
      description = ''
        Environment variables passed to *all* systemd units.
      '';
    };
    enableStrictShellChecks = lib.mkOption {
      type = types.bool;
      default = false;
      description = ''
        Whether to run `shellcheck` on the generated scripts for systemd
        units.

        When enabled, all systemd scripts generated by NixOS will be checked
        with `shellcheck` and any errors or warnings will cause the build to
        fail.

        This affects all scripts that have been created through the `script`,
        `reload`, `preStart`, `postStart`, `preStop` and `postStop` options for
        systemd services. This does not affect command lines passed directly
        to `ExecStart`, `ExecReload`, `ExecStartPre`, `ExecStartPost`,
        `ExecStop` or `ExecStopPost`.

        It therefore also does not affect systemd units that are coming from
        packages and that are not defined through the config. This option
        is disabled by default, and although some services have already been
        fixed, it is still likely that you will encounter build failures when
        enabling this.

        We encourage people to enable this option when they are willing and
        able to submit fixes for potential build failures to Nixpkgs. The
        option can also be enabled or disabled for individual services using
        the `enableStrictShellChecks` option on the service itself, which will
        take precedence over the global setting.
      '';
    };
  };

  config = {
    environment.systemPackages = [ cfg.package ];

    environment.etc."systemd/user".source = systemdUtils.lib.generateUnits {
      type = "user";
      package = cfg.package;
      packages = cfg.user.packages;
      units = cfg.user.units;

      upstreamUnits = [
        "app.slice"
        "background.slice"
        "basic.target"
        "bluetooth.target"
        "capsule@.target"
        "default.target"
        "exit.target"
        "graphical-session-pre.target"
        "graphical-session.target"
        "paths.target"
        "printer.target"
        "session.slice"
        "shutdown.target"
        "smartcard.target"
        "sockets.target"
        "sound.target"
        "systemd-exit.service"
        "timers.target"
        "xdg-desktop-autostart.target"
      ];
      upstreamWants = [ ];
    };

    finit.tasks =
      lib.mapAttrs'
        (
          username: _:
          lib.nameValuePair "hjem-reload-${username}" {
            description = "Reload systemd user units after Hjem activation for ${username}";
            user = username;
            conditions = [ "task/hjem-activate-${username}/success" ];
            command = pkgs.writeShellScript "hjem-reload-${username}" ''
              ${cfg.package}/bin/systemctl --user daemon-reload
            '';
          }
        )
        (
          lib.filterAttrs (_: user: user.enable && (user.systemd.enable or false)) (config.hjem.users or { })
        );

    # systemd --user checks if systemd system service manager is running
    # by checking this directory and refuses to start if it doesnt exist
    # despite it running perfectly fine standalone
    finit.tmpfiles.rules = lib.optionals (!config.services.elogind.enable) [
      "d /run/systemd/system 0755 root root -"
    ];

    systemd.user.units = trivial.pipe unitTypes [
      (map (
        t:
        attrsets.mapAttrsToList (
          n: v: attrsets.nameValuePair "${n}.${t}" (systemdUtils.lib."${t}ToUnit" v)
        ) cfg.user."${t}s"
      ))
      lists.flatten
      builtins.listToAttrs
    ];
  };
}
